# Generated by Django 4.2.20 on 2025-04-30 11:46

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='users_chat_unique',
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Greatest(models.F('user_1'), models.F('user_2')), django.db.models.functions.comparison.Least(models.F('user_1'), models.F('user_2')), name='users_chat_unique'),
        ),
    ]
